CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);

CREATE TYPE order_status AS ENUM (
    'NEW',
    'PROCESSING',
    'INVALID',
    'PROCESSED'
);

CREATE TABLE orders (
    number VARCHAR(32) PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    status order_status NOT NULL,
    accrual DOUBLE PRECISION,
    uploaded_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    order_number VARCHAR(32) NOT NULL,
    sum DOUBLE PRECISION NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_orders_user_id_uploaded_at
    ON orders(user_id, uploaded_at DESC);

CREATE INDEX idx_withdrawals_user_id_processed_at
    ON withdrawals(user_id, processed_at DESC);