package repository

import (
	"context"
	"errors"
	"time"

	"go-musthave-diploma/internal/model"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

type PostgresRepository struct {
	pool *pgxpool.Pool
}

func NewPostgresRepository(pool *pgxpool.Pool) *PostgresRepository {
	return &PostgresRepository{
		pool: pool,
	}
}

// CreateUser creates a new user with the given login and password hash.
//
// The user ID is auto-generated by the database. If a user with the same
// login already exists, returns ErrAlreadyExists.
//
// Parameters:
//   - ctx: Context for query cancellation and timeouts
//   - login: Unique username for the new user
//   - passwordHash: Bcrypt hash of the user's password
//
// Returns:
//   - *model.User: Pointer to the created user with assigned ID
//   - error: ErrAlreadyExists if login is taken, or database error
func (r *PostgresRepository) CreateUser(ctx context.Context, login string, passwordHash string) (*model.User, error) {
	const query = `
		INSERT INTO users (login, password_hash)
		VALUES ($1, $2)
		RETURNING id, login, password_hash
	`

	var user model.User
	err := r.pool.QueryRow(ctx, query, login, passwordHash).
		Scan(&user.ID, &user.Login, &user.PasswordHash)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == "23505" {
			return nil, ErrAlreadyExists
		}

		return nil, err
	}

	return &user, nil
}

// GetUserByLogin retrieves a user by their login username.
//
// Parameters:
//   - ctx: Context for query cancellation and timeouts
//   - login: Username to look up
//
// Returns:
//   - *model.User: Pointer to the user if found
//   - error: ErrNotFound if user doesn't exist, or database error
func (r *PostgresRepository) GetUserByLogin(
	ctx context.Context,
	login string,
) (*model.User, error) {
	const query = `
		SELECT id, login, password_hash
		FROM users
		WHERE login = $1
	`

	var user model.User

	err := r.pool.QueryRow(ctx, query, login).
		Scan(&user.ID, &user.Login, &user.PasswordHash)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound
		}

		return nil, err
	}

	return &user, nil
}

// CreateOrder creates a new order for the specified user.
//
// The order is created with status NEW and the current timestamp.
// If an order with the same number already exists, returns ErrAlreadyExists.
//
// Parameters:
//   - ctx: Context for query cancellation and timeouts
//   - userID: ID of the user uploading the order
//   - number: Unique order number
//
// Returns:
//   - error: ErrAlreadyExists if order exists, or database error
func (r *PostgresRepository) CreateOrder(ctx context.Context, userID int64, number string) error {
	const query = `
		INSERT INTO orders (number, user_id, status, uploaded_at)
		VALUES ($1, $2, $3, $4)
	`

	_, err := r.pool.Exec(
		ctx,
		query,
		number,
		userID,
		model.OrderStatusNew,
		time.Now(),
	)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == "23505" {
			return ErrAlreadyExists
		}

		return err
	}

	return nil
}

// GetOrderByNumber retrieves an order by its number.
//
// Parameters:
//   - ctx: Context for query cancellation and timeouts
//   - number: Order number to look up
//
// Returns:
//   - *model.Order: Pointer to the order if found
//   - error: ErrNotFound if order doesn't exist, or database error
func (r *PostgresRepository) GetOrderByNumber(ctx context.Context, number string) (*model.Order, error) {
	const query = `
		SELECT number, user_id, status, accrual, uploaded_at
		FROM orders
		WHERE number = $1
	`

	var order model.Order
	err := r.pool.QueryRow(ctx, query, number).
		Scan(&order.Number, &order.UserID, &order.Status, &order.Accrual, &order.UploadedAt)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound
		}

		return nil, err
	}

	return &order, nil
}

// GetOrdersByUserID retrieves all orders for a specific user.
//
// Orders are returned in descending order by upload timestamp (newest first).
//
// Parameters:
//   - ctx: Context for query cancellation and timeouts
//   - userID: ID of the user to retrieve orders for
//
// Returns:
//   - []model.Order: Slice of order records (may be empty)
//   - error: Database error
func (r *PostgresRepository) GetOrdersByUserID(
	ctx context.Context,
	userID int64,
) ([]model.Order, error) {
	const query = `
		SELECT number, user_id, status, accrual, uploaded_at
		FROM orders
		WHERE user_id = $1
		ORDER BY uploaded_at DESC
	`

	rows, err := r.pool.Query(ctx, query, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	orders := make([]model.Order, 0)

	for rows.Next() {
		var order model.Order

		if err := rows.Scan(
			&order.Number,
			&order.UserID,
			&order.Status,
			&order.Accrual,
			&order.UploadedAt,
		); err != nil {
			return nil, err
		}

		orders = append(orders, order)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return orders, nil
}

// GetWithdrawalsByUserID retrieves all withdrawals for a specific user.
//
// Withdrawals are returned in descending order by processing timestamp (newest first).
//
// Parameters:
//   - ctx: Context for query cancellation and timeouts
//   - userID: ID of the user to retrieve withdrawals for
//
// Returns:
//   - []model.Withdrawal: Slice of withdrawal records (may be empty)
//   - error: Database error
func (r *PostgresRepository) GetWithdrawalsByUserID(ctx context.Context, userID int64) ([]model.Withdrawal, error) {
	const query = `
		SELECT order_number, user_id, sum, processed_at
		FROM withdrawals
		WHERE user_id = $1
		ORDER BY processed_at DESC
	`

	rows, err := r.pool.Query(ctx, query, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var withdrawals []model.Withdrawal

	for rows.Next() {
		var withdrawal model.Withdrawal
		if err := rows.Scan(
			&withdrawal.Order,
			&withdrawal.UserID,
			&withdrawal.Sum,
			&withdrawal.ProcessedAt,
		); err != nil {
			return nil, err
		}

		withdrawals = append(withdrawals, withdrawal)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return withdrawals, nil
}

// GetOrdersForAccrual retrieves orders that need accrual processing.
//
// Returns orders with status NEW or PROCESSING, ordered by upload timestamp
// (oldest first), up to the specified limit.
//
// Parameters:
//   - ctx: Context for query cancellation and timeouts
//   - limit: Maximum number of orders to return
//
// Returns:
//   - []model.Order: Slice of orders awaiting accrual (may be empty)
//   - error: Database error
func (r *PostgresRepository) GetOrdersForAccrual(ctx context.Context, limit int) ([]model.Order, error) {
	const query = `
		SELECT number, user_id, status, accrual, uploaded_at
		FROM orders
		WHERE status IN ($1, $2)
		ORDER BY uploaded_at ASC
		LIMIT $3
	`

	rows, err := r.pool.Query(
		ctx,
		query,
		model.OrderStatusNew,
		model.OrderStatusProcessing,
		limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var orders []model.Order

	for rows.Next() {
		var order model.Order
		if err := rows.Scan(
			&order.Number,
			&order.UserID,
			&order.Status,
			&order.Accrual,
			&order.UploadedAt,
		); err != nil {
			return nil, err
		}

		orders = append(orders, order)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return orders, nil
}

// UpdateOrderAccrual updates the status and accrual amount for an order.
//
// Parameters:
//   - ctx: Context for query cancellation and timeouts
//   - number: Order number to update
//   - status: New status for the order
//   - accrual: Accrued points amount (nil if not applicable)
//
// Returns:
//   - error: Database error
func (r *PostgresRepository) UpdateOrderAccrual(ctx context.Context, number string, status model.OrderStatus, accrual *float64) error {
	const query = `
		UPDATE orders
		SET status = $2,
		    accrual = $3
		WHERE number = $1
	`

	_, err := r.pool.Exec(ctx, query, number, status, accrual)
	return err
}

func (r *PostgresRepository) GetBalance(ctx context.Context, userID int64) (*model.Balance, error) {
	const query = `
		WITH balance AS (
			SELECT
				COALESCE((
					SELECT SUM(accrual)
					FROM orders
					WHERE user_id = $1
				), 0) AS accrued,
				COALESCE((
					SELECT SUM(sum)
					FROM withdrawals
					WHERE user_id = $1
				), 0) AS withdrawn
		)
		SELECT
			accrued - withdrawn,
			withdrawn
		FROM balance
	`

	var balance model.Balance

	err := r.pool.QueryRow(ctx, query, userID).Scan(
		&balance.Current,
		&balance.Withdrawn,
	)
	if err != nil {
		return nil, err
	}

	return &balance, nil
}

func (r *PostgresRepository) Withdraw(
	ctx context.Context,
	userID int64,
	order string,
	sum float64,
) error {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer func() {
		_ = tx.Rollback(ctx)
	}()

	const lockUserQuery = `
		SELECT id
		FROM users
		WHERE id = $1
		FOR UPDATE
	`

	var lockedUserID int64
	if err := tx.QueryRow(ctx, lockUserQuery, userID).Scan(&lockedUserID); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return ErrNotFound
		}

		return err
	}

	const balanceQuery = `
		WITH balance AS (
			SELECT
				COALESCE((
					SELECT SUM(accrual)
					FROM orders
					WHERE user_id = $1
				), 0) AS accrued,
				COALESCE((
					SELECT SUM(sum)
					FROM withdrawals
					WHERE user_id = $1
				), 0) AS withdrawn
		)
		SELECT accrued - withdrawn
		FROM balance
	`

	var current float64
	if err := tx.QueryRow(ctx, balanceQuery, userID).Scan(&current); err != nil {
		return err
	}

	if current < sum {
		return ErrNotEnoughBalance
	}

	const createWithdrawalQuery = `
		INSERT INTO withdrawals (
			user_id,
			order_number,
			sum,
			processed_at
		)
		VALUES ($1, $2, $3, $4)
	`

	if _, err := tx.Exec(
		ctx,
		createWithdrawalQuery,
		userID,
		order,
		sum,
		time.Now(),
	); err != nil {
		return err
	}	

	return tx.Commit(ctx)
}

// GetWithdrawalSumByUserID calculates the total withdrawn points for a user.
//
// Uses COALESCE to return 0 if the user has no withdrawals.
//
// Parameters:
//   - ctx: Context for query cancellation and timeouts
//   - userID: ID of the user to calculate withdrawals for
//
// Returns:
//   - float64: Total withdrawn points (0 if none)
//   - error: Database error
func (r *PostgresRepository) GetWithdrawalSumByUserID(ctx context.Context, userID int64) (float64, error) {
	const query = `
		SELECT COALESCE(SUM(sum), 0)
		FROM withdrawals
		WHERE user_id = $1
	`

	var sum float64
	err := r.pool.QueryRow(ctx, query, userID).Scan(&sum)
	if err != nil {
		return 0, err
	}

	return sum, nil
}
